eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
#服务配置
server:
  port: 9002
#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-system #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8
    username: root
    password: qwe123..
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379
jwt:
  config:
    key: saas-ihrm
    ttl: 360000
#百度云人脸识别
ai:
  appId: 19622227
  apiKey: SZjekuXBmR0NiodOHTU9wKvp
  secretKey: AfOcwKpZs5v1mjlYm83FADX16ohUUesR
  imageType: BASE64
  groupId: guo
#扫描二维码后跳转的地址
qr:
  url: http://localhost:8080/#/facelogin

